// Code generated by hertz generator.

package main

import (
	"simpleTiktok/biz/dal"
	"simpleTiktok/biz/mw/jwt"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	dal.Init()
	jwt.InitJWT()
}

func main() {
	Init()
	h := server.Default(
		server.WithStreamBody(true),
		server.WithHostPorts("0.0.0.0:18080"),
	)

	register(h)
	h.Spin()
	
}
