// Code generated by hertz generator.

package main

import (
	handler "simpleTiktok/biz/handler"
	"simpleTiktok/biz/mw/jwt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", append([]app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	},handler.Ping)...)

	// your code ...
}
