// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	comment "simpleTiktok/biz/router/comment"
	favorite "simpleTiktok/biz/router/favorite"
	feed "simpleTiktok/biz/router/feed"
	message "simpleTiktok/biz/router/message"
	publish "simpleTiktok/biz/router/publish"
	relation "simpleTiktok/biz/router/relation"
	user "simpleTiktok/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	relation.Register(r)

	publish.Register(r)

	message.Register(r)

	feed.Register(r)

	favorite.Register(r)

	comment.Register(r)

}
